feat: UI Layer 에 변경된 이미지 API 반영
geezers-io/frolic-frontend pull request #14
Opened 2023-03-13 10:48 UTC by galaxy4276

## Type
- [x] Feature
- [ ] Fix

## What & Why
* static url 을 그대로 serving 하던 방식에서 rest api 로 변경 된 부분에 대해서 코드를 수정하였습니다.
* 기존에 `file.downloadUrl` 을 사용하던 부분에 대해서 api call 형태로 코드를 변경해두었습니다.

![image](https://user-images.githubusercontent.com/50310464/224680128-b9a40a31-09d1-47c3-94e4-ffeb8ae1aab2.png)
![이미지작업](https://user-images.githubusercontent.com/50310464/224680179-24070205-7e98-4f13-aba4-61cb5065aa93.gif)

## Checklist
- [x] If there is a related ticket(Jira), did you insert the ticket(Jira)? -> 지라없습니당.

2023-03-17 15:00 UTC, will-kim-querypie requested changes
대신 작업 감사합니다~

리뷰 내용들고 더불어 추가로 의견드리면,
* post/utils/image 의 getImageBlob 은 컴포넌트 내로 이동해도 문제 없어보입니다 (유틸로 분리할 정도로 복잡도가 높지 않아 보입니다)
* post/utils/image 의 getImageUrlsFromFiles 은 useFetchImageUrls 훅 내로 이동하는게 좋아보입니다. (훅 내부 아니더라도 파일 내부로)
* useFetchImageUrls 훅은 src/hooks 내부로 이동해주세요 (컨벤션에 따라 다르지만 이전에 작성하던 방식은 비즈니스로직 성격이 강한 훅이나 유틸이라도 src/ 하위에 두고 있습니다)

<img width="267" alt="스크린샷 2023-03-17 오후 11 56 21" src="https://user-images.githubusercontent.com/57123802/225941025-dc4364e2-9d42-43d1-be83-9ddb03aaa2e2.png">

2023-03-17 15:00 UTC, will-kim-querypie commented on src/api/services/file.ts
> +  },
[의견]
async await 으로 리팩터링하는건 어떨까요? 취향문제고 동작은 같지만, 기존 Service 하위 코드들이 모두 async await 방식을 사용하고 있습니다

``` ts
  async downloadFile(filename: string): Promise<Blob> {
    const res = await rawAxios.get<Blob>(`/file/${encodeURIComponent(filename)}`, {
      responseType: 'blob',
    });

    return new Blob([res.data]);
  },
```

2023-03-17 15:00 UTC, will-kim-querypie commented on src/components/post/hooks/useFetchImageUrls.tsx
> +};
[변경요청]
try catch 처리가 필요합니다
``` ts
export const useFetchImageUrls = (files: FileInfo[]) => {
  const [imageUrls, setImageUrls] = useState<string[]>([]);

  const getImageUrls = async (files: FileInfo[]) => {
    try {
      const imageUrls = await getImageUrlsFromFiles(files);
      setImageUrls(imageUrls);
    } catch (e) {
      message.error(e.message);
    }
  };

  useEffect(() => {
    getImageUrls(files);
  }, [files]);

  return imageUrls;
};
```

2023-03-17 15:00 UTC, will-kim-querypie commented on src/components/post/utils/image.ts
> +};
[의견]

리팩터링하는게 좋아보입니다. (map 2번 > 1번으로 축소, 함수 내부에서만 사용하는 유틸 함수 안으로 이동)

``` ts
export const getImageUrlsFromFiles = async (files: FileInfo[]): Promise<string[]> => {
  const blobs = await Promise.all(
    files.map((file) => {
      return downloadFile(file.filename);
    })
  );

  return blobs.map(URL.createObjectURL);
};

```

2023-03-17 15:00 UTC, will-kim-querypie commented on src/pages/index.tsx
> +        const posts = await PostsService.getPosts({ cursorId });
[질문]

count(size) 는 안 받으시나요? (고정인가요?)

2023-03-17 21:50 UTC, galaxy4276 commented on src/components/post/hooks/useFetchImageUrls.tsx
> +};
그러네요 확인해주셔서 감사합니다.

2023-03-17 21:54 UTC, galaxy4276 commented on src/components/post/utils/image.ts
> +};
map 2회에 대해 저도 코드를 작성하면서 고민을 많이 했는데요.
함수형 메서드들의 chain 형태가 이루어지면서 가독성을 좀 더 챙겨가고자 다음과 같이 작성하게 되었습니다.
다만 chain 형태가 아닌 각 함수들을 함수형 패턴 중 pipe 또는 go 를 이용했으면 더 바람직했을 것 같고 지금과 같은 방식에서는 
의견 주셨던 대로 변경하는게 좋을지도 모르겠네요.
 
TL;DR 함수형 프로그래밍을 실현하고자 다음과 같이 작성하였으나 변경하겠습니다.

2023-03-17 21:56 UTC, galaxy4276 commented on src/pages/index.tsx
> +        const posts = await PostsService.getPosts({ cursorId });
네 클라이언트에서 받고싶은 개수를 요청하는 것은 "구현에 드는 비용 대비 필요로 하는 기능인가?" 에 대해 필요하다고 판단되지 않았습니다.

2023-03-17 22:00 UTC, galaxy4276 commented on src/api/services/file.ts
> +  },
컨벤션을 유지하자는 의견이 전적으로 동의하는 바입니다.

개인적인 의견으로서 해당 로직의 async/await 구문은 내부적으로 추가적인 제네레이터 연산이 수행되기 때문에 필요로 하지 않는다면 저는 사용하지 않습니다.
성능에 영향이 있는가? 하면 단순히 Syntax Sugar 이긴 합니다.
재밌게도, 현재 코드 리뷰 해주셨던 부분 중 [map 로직 횟수 축소](https://github.com/geezers-io/frolic-frontend/pull/14#discussion_r1140343222) 와 맥락이 비슷한 것 같네요. ( 성능 부분에서 좀 더 이점을 챙기자! 라는 의견으로 보았는데 그렇다면 해당 리뷰와 현재 리뷰에서 저희 둘의 입장이 바뀌어있네요 ㅋㅋ  )

2023-03-17 22:15 UTC, bear-bear-bear commented on src/api/services/file.ts
> +  },
엄.. async/await 사용하면서 성능을 얘기하는건 처음 듣는 의견이네요. 전 전혀 신경쓰지 않아도 될 정도라 생각합니다. 이게 반복문으로 엄청나게 돌아가는 것도 아니구요, 혹시 반복문에서라도 제가 모르던 유의미한 차이가 있을까 싶어 퍼포먼스 테스트를 해봤을때 1000 회 반복 기준 100ms (0.01초) 차이 납니다.

map 은 맥락이 다른게, 두 번 돌리면 n2(제곱) 입니다 (n1 로 바꾼다고 가독성을 해친다고 보기도 어렵구요)

2023-03-17 22:17 UTC, galaxy4276 commented
@bear-bear-bear  

> post/utils/image 의 getImageBlob 은 컴포넌트 내로 이동해도 문제 없어보입니다 (유틸로 분리할 정도로 복잡도가 높지 않아 보입니다)

관심사 분리를 통해 분리 처리한 모델을 다시 VIew 컴포넌트에 병합해야하는 것에 근거가 궁금합니디.

또한 이 부분에 관해서 제 개인적인 철학에 대해 말씀드리고 싶습니다.
소프트웨어를 설계할 때는 저는 우선적으로 추 후 유지보수에 용이한 구조로 애플리케이션을 설계합니다 즉, 제가 발휘할 수 있는 설계 능력 상 최대한 확장에 용이하고 변경에는 폐쇄적인 구조를 설계해두는 것인데요.
그러기 위한 첫 번째로 가장 쉽게 신경써줄 수 있는 부분이 한 객체(컴포넌트)가 수행하는 기능들을 분별하여 추상적으로 도메인을 분리하는 것입니다.
( 해당 컴포넌트로서는 네트워크 IO, View, UI 비즈니스 로직 정도로 분류할 수 있겠네요. )
이제 이 부분에서 핵심은 Inversion of Control 을 수행하여 도메인 별에서 각 책임을 다른 객체에 지니게 함으로써 컴포넌트가 수행하는 일을 줄임으로써 컴포넌트를 순수하게 View 컴포넌트로 유지하고 경량화하는 것이겠네요.
이렇게 됨으로써 실제로 다른 개발자가 해당 컴포넌트를 확인했을 때 오로지 컴포넌트의 View 구조를 한 눈에 간결히 파악을 수행하고 컴포넌트 자체도 View 만을 보여주는 기능이 충실하게 되어 전반적으로 애플리케이션 복잡도가 줄어든다고 생각합니다.

2023-03-17 22:20 UTC, galaxy4276 commented on src/api/services/file.ts
> +  },
성능을 지적한게 아닙니다.
다만 제 개인적인 의견을 전달드린거에요. ( 필요로 하지 않는 로직을 사용하는 부분에 대해서 )
map 로직또한 다른 이야기지만 순수하게 자료구조 형태로 보았을 때 @bear-bear-bear 님 말씀이 맞습니다.
하지만 해당 로직에서는 async/await 성능 이야기를 해주셨던 것 처럼 유의미한 차이를 제공하지는 않지요.
또 그건 다른이야기인게 저는 함수형 측면에서 접근했던 부분입니다.

2023-03-17 22:25 UTC, bear-bear-bear commented
@galaxy4276 

다양한 자료와 경험으로 학습한 주관은 젠장 너무 멋지군요..

가장 큰건 기존 코드 구조와의 괴리입니다. 기존 코드 구조에 익숙한, 혹은 (없겠지만) 새로 코드를 익혀나갈 사람에게 낯선 느낌을 줍니다. 이건 일종의 디자인 패턴이고 컨벤션이라고 생각합니다 (뭐가 옳다 그르다의 문제가 아닌), 실제로 저희 회사 팀에서도 일전에는 은기님이 말씀하신대로, 현재는 제가 말하는 방향으로 코드를 작성하고 있져. 새로운 시도는 항상 좋지만, 시도하기 전 팀원간 충분한 논의를 거쳐야하고 새로운 방향으로 나아가기 위한 비용을 감수하는 것도 생각해야 합니다 (이 경우는, 앞으로 이렇게 구조를 뒤집고자 하면 일부만 건드리는게 아닌 프로젝트 전체를 바꿔야 하는게 맞음)

2023-03-20 22:06 UTC, galaxy4276 commented
피드백 반영 완료하였습니다.

* post/utils/image 의 getImageBlob 은 컴포넌트 내로 이동해도 문제 없어보입니다 (유틸로 분리할 정도로 복잡도가 높지 않아 보입니다)
* post/utils/image 의 getImageUrlsFromFiles 은 useFetchImageUrls 훅 내로 이동하는게 좋아보입니다. (훅 내부 아니더라도 파일 내부로)
 > 요청하신 내용을 반영할 경우, 훅을 제공하는 모듈에서 유틸 메서드를 훅을 사용하지 않은 외부 컴포넌트에서 import 하는 현상이 발생하여 유틸성 함수는 utils/image.ts 로 이동하였습니다.

* useFetchImageUrls 훅은 src/hooks 내부로 이동해주세요 (컨벤션에 따라 다르지만 이전에 작성하던 방식은 비즈니스로직 성격이 강한 훅이나 유틸이라도 src/ 하위에 두고 있습니다)
 > 반영하였습니다.

2023-03-25 14:57 UTC, bear-bear-bear approved these changes

2023-03-26 14:24 UTC, merged